### PR TITLE
Replace the deprecated gulp-util with plugin-error.

### PR DESCRIPTION
**Pull request by XhmikosR**
/CC @macedigital 

See also https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5

### CODE REVIEW

**Comment by macedigital** [comment]
@XhmikosR Thanks, yes, let's help fix the gulp ecosystem!

**Comment by XhmikosR** [comment]
@macedigital: maybe you could try updating any deps and release a new version?

**Comment by macedigital** [comment]
@XhmikosR Yes, I'm in the process. Expect a new release soon-ish.

**Comment by XhmikosR** [comment]
Thanks!

**Pull request merged**
